### PR TITLE
Add 'setItem' function

### PR DESCRIPTION
**Pull request by gabriel1lima**
Using the `controller` ref, it is possible to set the selected item.

### CODE REVIEW

**Comment by stevendeng-ddi** [comment]
upgraded to 2.0.4, it complains the "setItem" function is not defined when i tried to call it.

**Comment by onmotion** [comment]
could you please share the code? 
Basically you should do 
1 Get access to the ref 

```js
const dropdownController = useRef(null)

<AutocompleteDropdown
          controller={controller => {
            dropdownController.current = controller
          }}
/>
```

2 Call the method
```js
<Button title="Toggle" onPress={() => dropdownController.current.setItem({id: "1", title: "test"})} />
```

**Comment by onmotion** [comment]
Oh, you're right, it's just a ts interface omission. I'll fix it now.

**Comment by stevendeng-ddi** [comment]
Awesome!  I will grab latest and give it a swirl! Thank you!

**Comment by onmotion** [comment]
Try `2.0.5`

**Comment by stevendeng-ddi** [comment]
Hi again,  thank you for the prompt help. I downloaded 2.0.5 and got the same error ... I notice that "setInput" was added but not "**setItem**" , and setItem also takes one parameter.

**Comment by onmotion** [comment]
damn. I'm sorry :) Now `2.0.6`

**Comment by stevendeng-ddi** [comment]
:( I downlowned 2.0.6 and still got the same error ... I did a log for the controller, and I don't see setItem method... I am probably missing something ... I did a cache reset a few times, but no luck so far .... 

            controller={(controller) => {
              console.log({controller});
              dropdownController.current = controller;
            }}

 LOG  {"controller": {"clear": [Function clear], "close": [Function close], "open": [Function open], "setInputText": [Function setInputText], "toggle": [Function toggle]}}

**Comment by onmotion** [comment]
can you go to node_modules/react-native-autocomplete-dropdown/package.json and make sure that `"version": "2.0.6"`?

**Comment by stevendeng-ddi** [comment]
It finally works 👍. Thank you so much for the prompt help today! 
I turned off my emulator and ran "yarn start --reset-cache" one more time.  And then fired up the app again and this time I can see the setItem function exposed 

 LOG  {"controller": {"clear": [Function clear], "close": [Function close], "open": [Function open], "setInputText": [Function setInputText], "**setItem**": [Function setItem], "toggle": [Function toggle]}}

**Pull request merged**
